### ISSUE TITLE
minilua.h:987: error: ')' expected (got "2")

### ISSUE THREAD

**Issue by darltrash** [edubart/minilua#2]
just as the title says, whenever I try to include this library, that error happens...
![imagen](https://github.com/edubart/minilua/assets/38925212/054462f5-ab54-40fd-b692-52309ea34a25)

**Comment by edubart** [comment]
You should share more details about your toolchain and system. Also could be the case that your own code is conflicting with the minilua.h code, like a define with the same name.

Also try to define minilua implementation in a dedicated C file, as the README suggests, to avoid conflicting names.

**Comment by darltrash** [comment]
Oh, adding it to a separate file worked, thanks!
